/**
 * i-Spy Insights content collection.
 *
 * Add future articles here, then run `npm run build:insights`. The generator
 * updates the listing page, article routes, related cards and XML sitemap.
 */

module.exports = [
  {
    title: "Values are better as verbs",
    standfirst: "Good values don’t just describe a business. They give people clear, memorable behaviours to use when decisions get difficult.",
    slug: "values-are-better-as-verbs",
    category: "Brand",
    tags: ["brand values", "culture", "behaviour", "leadership", "brand strategy"],
    readingTime: "3 min read",
    metaTitle: "Values Are Better as Verbs | i-Spy Insights",
    metaDescription: "Why practical, verb-led values are easier to remember, easier to imagine and more useful in shaping everyday business behaviour.",
    publicationDate: "2026-07-21",
    modifiedDate: "2026-07-22",
    listingOrder: 2,
    images: [],
    body: [
      { type: "p", html: "Many businesses have values. Fewer can point to the moment those values changed a decision, raised a standard or made a difficult conversation easier." },
      { type: "p", html: "That’s the difference between a list of admirable words and a useful operating principle." },
      { type: "h2", text: "A value should tell people what to do" },
      { type: "p", html: "The All Blacks have a phrase: <strong>Sweep the Sheds</strong>." },
      { type: "p", html: "After a match, some of the biggest names in the team help clean the changing room. It’s a simple instruction with a clear meaning: nobody is above the team." },
      { type: "p", html: "It works because it asks people to do something. It doesn’t rely on a broad word such as teamwork or humility and expect everyone to interpret it in the same way. It turns the principle into visible behaviour." },
      { type: "h2", text: "Generic values aren’t enough" },
      { type: "p", html: "Honesty, integrity and professionalism all matter, but they should be expected rather than presented as the defining character of a business." },
      { type: "p", html: "They don’t tell a team what makes the organisation different, what standard to apply when the pressure is on or what to do when the answer isn’t obvious." },
      { type: "p", html: "Strong values make that connection. They translate the ambition of the business into everyday choices about how people work together, serve customers and decide what good looks like." },
      { type: "h2", text: "At i-Spy, the values start with action" },
      { type: "p", html: "Each i-Spy value deliberately begins with a verb:" },
      { type: "ul", items: ["Enjoy the Ride", "Look Again", "Keep It Human", "Sweat the Thinking, Not the Theatre", "Find a Better Way"] },
      { type: "p", html: "Enjoy. Look. Keep. Sweat. Find." },
      { type: "p", html: "They’re instructions rather than labels. Each one prompts action by framing the value as something people can do, rather than an abstract noun they’re expected to admire." },
      { type: "p", html: "The language is deliberately familiar too. These are simple statements made from words people already use, rather than corporate language that needs to be decoded or translated into everyday life." },
      { type: "p", html: "They also give the imagination something to work with: a ride, a second look, a human response, unnecessary theatre and a better way waiting to be found." },
      { type: "p", html: "Research into memory suggests that concrete, imageable words are often easier to process and remember than abstract ones. That doesn’t mean a cleverly worded value will create a strong culture by itself, but it can remove one of the barriers to people remembering and using it." },
      { type: "p", html: "For a growing business, that matters. Values can establish direction early, make expectations visible and give people a shared way to move forward without adding unnecessary process." },
      { type: "p", html: "The best values don’t simply describe a business. They help people decide how to behave within it." },
      { type: "p", html: "So the question isn’t whether your business has values. It’s whether anyone can use them tomorrow." }
    ],
    didYouKnow: [
      { html: "“Sweep the Sheds” is closely associated with the culture of New Zealand’s All Blacks and was explored in James Kerr’s book <em>Legacy</em>." },
      "Studies of memory have found that concrete words can be easier to recall and recognise than abstract ones.",
      "All five i-Spy values begin with a verb and are written as everyday instructions rather than abstract nouns."
    ],
    related: ["levis-gillette-attention-recognition", "sales-starts-before-the-pitch"],
    cta: null
  },
  {
    title: "Levi’s and Gillette: the difference between attention and recognition",
    standfirst: "Levi’s and Gillette used the same World Cup moment very differently. One borrowed attention. The other showed the accumulated power of a distinctive brand asset.",
    slug: "levis-gillette-attention-recognition",
    category: "Brand",
    tags: ["distinctive brand assets", "recognition", "social media", "reactive marketing", "Levi’s", "Gillette", "FIFA World Cup"],
    readingTime: "3 min read",
    metaTitle: "Levi’s and Gillette: Attention and Recognition | i-Spy",
    metaDescription: "What Levi’s and Gillette’s World Cup responses reveal about reactive marketing, recognition and the time it takes to build distinctive brand assets.",
    publicationDate: "2026-07-21",
    modifiedDate: "2026-07-22",
    listingOrder: 1,
    images: [
      { id: "levis-stadium", src: "/images/insights/levis-gillette/levis-stadium-covered.jpg", width: 1206, height: 1203, alt: "Levi’s Stadium sign covered by a white sheet, leaving the familiar batwing logo shape visible." },
      { id: "gillette-stadium", src: "/images/insights/levis-gillette/gillette-stadium-foam.jpg", width: 1206, height: 1273, alt: "Computer-generated visual of Gillette Stadium with the name covered by shaving foam." },
      { id: "levis-instagram", src: "/images/insights/levis-gillette/levis-instagram-profile.jpg", width: 991, height: 525, alt: "Levi’s Instagram profile using a white-covered batwing logo during the 2026 World Cup.", caption: "Levi’s carried the covered-logo idea into its social identity." }
    ],
    listingImage: "levis-stadium",
    body: [
      { type: "p", html: "Levi’s and Gillette both responded to FIFA’s 2026 World Cup branding restrictions by covering their names. One showed what happens when a business owns a genuinely distinctive brand asset. The other showed the value, and the limit, of reactive marketing." },
      { type: "p", html: "At Levi’s Stadium, the company’s name had to be obscured to meet FIFA’s clean-stadium requirements. Levi’s embraced the restriction, allowing the familiar batwing shape to remain visible beneath the covering. It then carried the idea into its social identity and selected stores." },
      { type: "p", html: "Gillette joined the conversation with a computer-generated image showing its stadium name covered by shaving foam. It was quick, relevant and well matched to the product category." },
      { type: "comparison", images: ["levis-stadium", "gillette-stadium"], caption: "Similar World Cup responses, but only one asset could identify the brand without supporting context." },
      { type: "inset", image: "levis-instagram" },
      { type: "p", html: "On the face of it, both brands had made the same move: cover the name, create some intrigue and let social media spread the idea." },
      { type: "p", html: "But the results weren’t the same." },
      { type: "p", html: "Without surrounding context, Gillette’s shaving foam is a category cue. It points towards shaving, but it doesn’t belong uniquely to Gillette. Someone needs to see the image on Gillette’s account, know who sponsors the stadium or read the accompanying conversation to understand the joke." },
      { type: "p", html: "Take that context away and it’s foam on a stadium." },
      { type: "p", html: "Levi’s needed less explanation. The shape left beneath the covering had been used consistently for long enough that it could still bring the brand to mind without the name being fully visible." },
      { type: "p", html: "That’s the difference between attention and recognition." },
      { type: "p", html: "Gillette successfully joined a live cultural conversation and gained extra visibility from an idea Levi’s had already made interesting. That has value. Reactive marketing can be fast, funny and commercially useful." },
      { type: "p", html: "But it isn’t the same as owning an asset people recognise independently." },
      { type: "h2", text: "Distinctive assets aren’t built during a campaign" },
      { type: "p", html: "Strong distinctive assets need two qualities: fame and uniqueness." },
      { type: "p", html: "Fame means enough people connect the asset to the brand. Uniqueness means they connect it to that brand rather than several competitors." },
      { type: "p", html: "There isn’t an honest formula that says an asset becomes distinctive after three years, five campaigns or a particular level of media spend. It depends on reach, consistency, competitive similarity and how reliably the asset is linked to the brand." },
      { type: "p", html: "What’s clear is that it doesn’t happen overnight." },
      { type: "p", html: "People learn brand assets through repeated exposure across advertising, products, packaging, places and experiences. Businesses have to keep using them consistently enough, and for long enough, to give the public a realistic chance to remember them." },
      { type: "p", html: "Levi’s batwing was created in 1967. It had nearly six decades of exposure behind it by the time FIFA asked the company to cover its name." },
      { type: "p", html: "This is the part many businesses underestimate. They invest in a new identity, use it inconsistently for a few years and replace it before the market has had enough time to learn it." },
      { type: "p", html: "Young brands should be particularly careful. A newly launched symbol might feel familiar inside the business because the team has spent months discussing it. The wider public may have seen it only once, if at all." },
      { type: "p", html: "Distinctive assets aren’t campaign decoration. They become mental shortcuts through repeated public exposure." },
      { type: "p", html: "Gillette entered the conversation quickly. Levi’s demonstrated the accumulated commercial value of being recognised without needing to introduce itself." }
    ],
    didYouKnow: [
      "Levi Strauss & Co. was founded in 1853, while Gillette traces its business to 1901.",
      "The Levi’s batwing logo was created in 1967, nearly sixty years before the 2026 World Cup.",
      "Levi’s extended the covered-logo idea into stores and social profiles, while Gillette’s shaving-foam stadium image was created for social media."
    ],
    related: ["values-are-better-as-verbs", "sales-starts-before-the-pitch"],
    cta: null
  },
  {
    title: "Sales starts before the pitch",
    standfirst: "A 1958 advert still explains a modern commercial truth: brand-building makes the salesperson’s job easier before the meeting begins.",
    slug: "sales-starts-before-the-pitch",
    category: "Business",
    tags: ["sales", "brand building", "B2B marketing", "reputation", "awareness", "business development"],
    readingTime: "3 min read",
    metaTitle: "Sales Starts Before the Pitch | i-Spy Insights",
    metaDescription: "What a famous 1958 McGraw-Hill advert still teaches businesses about brand awareness, trust and making sales conversations easier.",
    publicationDate: "2026-07-21",
    listingOrder: 3,
    images: [
      {
        id: "mcgraw-hill-advert",
        src: "/images/insights/sales-before-the-pitch/mcgraw-hill-man-in-chair.jpg",
        width: 1834,
        height: 1146,
        alt: "A 1958 McGraw-Hill advertisement showing a seated business buyer beside a list of things they don’t know about a salesperson and their company.",
        caption: "McGraw-Hill’s 1958 “Man in the Chair” advertisement."
      }
    ],
    modifiedDate: "2026-07-22",
    listingImage: "mcgraw-hill-advert",
    body: [
      { type: "p", html: "Sales Directors struggling to open doors might recognise the problem in this 1958 advert." },
      { type: "p", html: "Created for McGraw-Hill, the advert commonly known as <em>The Man in the Chair</em> offers a remarkably simple explanation of why brand-building helps businesses sell." },
      { type: "image", image: "mcgraw-hill-advert" },
      { type: "p", html: "The prospective buyer in the image doesn’t know the salesperson, the company, its product, its customers, its record, its reputation or what it stands for." },
      { type: "p", html: "Only after making that clear do they ask:" },
      { type: "blockquote", html: "Now, what was it you wanted to sell me?" },
      { type: "p", html: "The advert was created long before social media, digital advertising, marketing automation and modern customer relationship systems. Yet the commercial problem it describes remains familiar." },
      { type: "p", html: "Sales teams are often asked to create demand, establish credibility, explain the business, differentiate the offer and close the opportunity within the same conversation." },
      { type: "p", html: "That’s too much to place on the pitch alone." },
      { type: "p", html: "Brand-building does some of that work before the salesperson arrives. It helps potential customers recognise the company, understand its relevance and form an initial judgement about whether it appears credible." },
      { type: "p", html: "That doesn’t mean every prospect needs to know or admire the brand before speaking to Sales. It also doesn’t mean brand activity can compensate for a weak offer or an ineffective sales process." },
      { type: "p", html: "It means the starting position matters." },
      { type: "p", html: "A salesperson entering a conversation on behalf of a known and clearly positioned business begins somewhere different from someone representing a company the buyer hasn’t encountered or can’t distinguish from its competitors." },
      { type: "p", html: "The strongest sales and marketing systems don’t operate as separate departments handing leads backwards and forwards. They build familiarity and confidence over time, then convert that advantage through a relevant commercial conversation." },
      { type: "p", html: "Lots has changed since 1958. Familiarity and credibility still change the starting position of a sales conversation." },
      { type: "p", html: "Sales success still begins before the pitch." }
    ],
    didYouKnow: [
      "The advert was created in 1958 by Gilbert Morris of the Fuller & Smith & Ross agency.",
      "Morris also appeared as the prospective buyer in the photograph.",
      { html: "In 1999, it was named the best business-to-business advert of the twentieth century by <em>Advertising Age’s Business Marketing</em>." }
    ],
    related: ["values-are-better-as-verbs", "levis-gillette-attention-recognition"],
    cta: null
  },
  {
    title: "People do judge a book by its cover",
    standfirst: "An early Apple marketing philosophy contained only three principles. Nearly 50 years later, they still explain why perception, focus and customer understanding matter.",
    slug: "people-do-judge-a-book-by-its-cover",
    category: "Brand",
    tags: ["Apple", "brand perception", "customer empathy", "focus", "presentation", "marketing strategy"],
    readingTime: "3 min read",
    metaTitle: "People Do Judge a Book by Its Cover | i-Spy Insights",
    metaDescription: "What Apple’s 1977 principles of Empathy, Focus and Impute teach businesses about customer understanding, clear choices and brand perception.",
    publicationDate: "2026-07-21",
    modifiedDate: "2026-07-22",
    listingOrder: 4,
    images: [
      {
        id: "apple-marketing-philosophy",
        src: "/images/insights/apple-marketing-philosophy/apple-marketing-philosophy-1977.jpg",
        width: 1206,
        height: 1505,
        alt: "Apple’s 1977 marketing philosophy setting out the principles of Empathy, Focus and Impute.",
        caption: "Mike Markkula’s one-page Apple Marketing Philosophy, dated 3 January 1977.",
        listingFit: "contain",
        enlargeable: true,
        enlargeLabel: "Enlarge the Apple Marketing Philosophy document"
      }
    ],
    listingImage: "apple-marketing-philosophy",
    body: [
      { type: "p", html: "People have always judged businesses by what they can see." },
      { type: "p", html: "A strong product matters, but before someone has used it, tested it or learned to trust it, they rely on signals. They judge the name, design, presentation, language, confidence, people and overall feeling surrounding it." },
      { type: "p", html: "That perception can be shaped." },
      { type: "p", html: "In January 1977, Mike Markkula wrote an early marketing philosophy for the young Apple business. It was built around just three principles:" },
      { type: "p", html: "<strong>Empathy. Focus. Impute.</strong>" },
      { type: "image", image: "apple-marketing-philosophy" },
      { type: "p", html: "Markkula was an early Apple investor and senior influence on the company. His document helped establish an approach that brought customer understanding, business discipline and presentation together from the start." },
      { type: "p", html: "Nearly 50 years later, those principles still offer a useful way to think about brand and marketing." },
      { type: "h2", text: "Empathy: understand people properly" },
      { type: "p", html: "Apple’s first principle was to understand customers’ needs better than anyone else." },
      { type: "p", html: "That sounds obvious, but many businesses begin from the opposite direction. They focus on what they’ve made, what they want to sell and what they need the market to understand." },
      { type: "p", html: "Empathy starts with the person on the other side." },
      { type: "p", html: "What are they trying to achieve? What frustrates them? What feels unnecessarily difficult? What would make the product feel useful rather than merely technically impressive?" },
      { type: "p", html: "Jobs was famously sceptical of asking customers to describe the next product, but that wasn’t the same as ignoring people. Apple’s approach was to interpret human needs beyond the most literal product request." },
      { type: "h2", text: "Focus: remove what doesn’t matter" },
      { type: "p", html: "The second principle was focus." },
      { type: "p", html: "To do a good job on the things Apple chose to pursue, Markkula argued that the business had to eliminate unimportant opportunities." },
      { type: "p", html: "That’s harder than it sounds." },
      { type: "p", html: "Businesses often confuse growth with addition. More services, more messages, more audiences and more features can feel like progress. In reality, they can make the proposition harder to understand and the organisation harder to run." },
      { type: "p", html: "Focus creates confidence. It tells employees where effort should go and helps customers understand what the business wants to be known for." },
      { type: "h2", text: "Impute: presentation shapes perception" },
      { type: "p", html: "The third principle is perhaps the most interesting." },
      { type: "p", html: "Markkula recognised that people do judge a book by its cover. Even a brilliant product could be perceived as careless if it was presented carelessly. Creative and professional presentation could help people recognise the quality within it." },
      { type: "p", html: "That isn’t superficial. It’s how people make decisions when they don’t yet have complete information." },
      { type: "p", html: "A prospective customer can’t inspect every internal process before buying. They look for evidence. Design, language, packaging, service and behaviour become signals of what they’re likely to experience." },
      { type: "p", html: "Done well, those signals create confidence. Confidence helps build trust. Trust makes demand more likely." },
      { type: "p", html: "That’s why brand-building isn’t decoration. It’s part of the commercial infrastructure around the product." },
      { type: "p", html: "Apple’s philosophy didn’t begin with advertising channels or sales tactics. It began with people, choices and perception." },
      { type: "p", html: "That remains a useful place for almost any business to start." }
    ],
    didYouKnow: [
      "The Apple Marketing Philosophy is dated 3 January 1977 and fits on a single page.",
      "Markkula’s framework contained only three principles: Empathy, Focus and Impute.",
      "The document was written while Apple was still a young business, making customer understanding and presentation part of its early thinking rather than later additions."
    ],
    related: ["your-origin-story-is-a-brand-asset", "values-are-better-as-verbs"],
    cta: null
  },
  {
    title: "Gen Z isn’t rejecting AI. It’s questioning the deal.",
    standfirst: "Young audiences are already using AI, but that doesn’t mean they’ll accept every way brands, universities and employers choose to deploy it.",
    slug: "gen-z-ai-questioning-the-deal",
    category: "Technology",
    tags: ["Gen Z", "artificial intelligence", "education", "early careers", "authenticity", "trust", "employer brand"],
    readingTime: "3 min read",
    metaTitle: "Gen Z, AI and the Growing Question of Trust | i-Spy",
    metaDescription: "Why Gen Z’s use of AI doesn’t remove the reputational risks for universities, employers and brands replacing visible human value with synthetic content.",
    publicationDate: "2026-07-21",
    modifiedDate: "2026-07-22",
    listingOrder: 5,
    images: [],
    body: [
      { type: "p", html: "AI is already part of student life." },
      { type: "p", html: "Young people use it to research, organise ideas, improve writing, solve problems and work more efficiently. That doesn’t mean they’re comfortable with everything AI represents." },
      { type: "p", html: "During the 2026 university graduation season in the United States, speeches celebrating artificial intelligence were met with audible opposition from students at several ceremonies. Former Google CEO Eric Schmidt was booed while discussing AI at the University of Arizona." },
      { type: "p", html: "The reaction wasn’t necessarily a rejection of technology itself. It reflected anxiety about employment, fairness and a future in which graduates are being told to embrace the same systems they fear may reduce their opportunities." },
      { type: "p", html: "That tension matters for universities, employers and brands trying to build genuine relationships with younger audiences." },
      { type: "h2", text: "Using AI doesn’t automatically mean trusting it" },
      { type: "p", html: "A student may use AI every day and still dislike a university replacing human guidance with a chatbot. They may use it to help structure an application while resenting an employer that fills its recruitment campaign with synthetic people." },
      { type: "p", html: "They may enjoy experimenting with image generation but question a brand that uses it primarily to replace photographers, illustrators, writers or other creatives." },
      { type: "p", html: "That isn’t hypocrisy. People regularly use systems while questioning how powerful organisations deploy them." },
      { type: "p", html: "Research into student attitudes has found a similarly complicated picture. Students recognise benefits including study support, brainstorming, feedback and access to information, while also expressing concerns about accuracy, privacy, ethics, career prospects and the effect on personal development." },
      { type: "p", html: "The issue isn’t simply whether AI was used. It’s what the organisation used it for, what it replaced and whether the audience was treated honestly." },
      { type: "h2", text: "The reputational risk sits in the trade-off" },
      { type: "p", html: "For brands, the temptation is obvious. AI can make communication quicker and cheaper. It can increase output and help small teams do more." },
      { type: "p", html: "But efficiency has a visible trade-off when the work starts to feel automated, synthetic or disconnected from real human experience." },
      { type: "p", html: "A university using AI to make information easier to access may be helping students. A university using artificial student imagery while talking about belonging may create the opposite impression." },
      { type: "p", html: "An early-careers employer using AI to answer routine questions could be useful. Using it to remove every meaningful human contact point may suggest that efficiency matters more than candidates." },
      { type: "p", html: "A brand using AI to explore ideas behind the scenes may face little resistance. Passing synthetic people or experiences off as real is more likely to damage trust." },
      { type: "p", html: "The safest principle may be this:" },
      { type: "p", html: "<strong>Use AI to support human value, not to disguise its removal.</strong>" },
      { type: "p", html: "Gen Z isn’t one audience with one opinion. Some will enthusiastically embrace the technology. Others will resist it. Most will probably sit somewhere between those positions." },
      { type: "p", html: "Brands don’t need to decide whether a generation is for or against AI. They need to show that they understand the human consequences of how they use it." }
    ],
    didYouKnow: [
      "A significant proportion of US college students surveyed have said they see AI as a threat to their employment prospects.",
      "Former Google CEO Eric Schmidt was booed while discussing AI at a University of Arizona graduation ceremony in 2026.",
      "University research has found enthusiasm for AI’s learning benefits alongside concerns about accuracy, privacy, ethics and future careers."
    ],
    related: ["sales-starts-before-the-pitch", "people-do-judge-a-book-by-its-cover"],
    cta: null
  },
  {
    title: "Your origin story is a brand asset",
    standfirst: "Competitors can copy products, services and promises. They can’t own the people, decisions and experiences that shaped your business.",
    slug: "your-origin-story-is-a-brand-asset",
    category: "Brand",
    tags: ["brand story", "origin story", "Nike", "Apple", "Virgin", "differentiation", "brand strategy"],
    readingTime: "4 min read",
    metaTitle: "Your Origin Story Is a Brand Asset | i-Spy Insights",
    metaDescription: "What the beginnings of Nike, Apple and Virgin show about using a genuine origin story to build difference, credibility and future direction.",
    publicationDate: "2026-07-21",
    modifiedDate: "2026-07-22",
    listingOrder: 6,
    images: [
      {
        id: "nike-bill-bowerman",
        src: "/images/insights/origin-story/nike-bill-bowerman.jpg",
        width: 625,
        height: 351,
        alt: "Phil Knight standing beside a display of Nike running shoes.",
        caption: "Nike co-founder Phil Knight with a display of early Nike shoes."
      },
      {
        id: "apple-early-team",
        src: "/images/insights/origin-story/apple-early-team.jpg",
        width: 1280,
        height: 720,
        alt: "Steve Jobs, John Sculley and Steve Wozniak presenting the Apple IIc on stage.",
        caption: "Steve Jobs, John Sculley and Steve Wozniak introduce the Apple IIc in 1984."
      },
      {
        id: "richard-branson-virgin-atlantic",
        src: "/images/insights/origin-story/richard-branson-virgin-atlantic.jpg",
        width: 1200,
        height: 846,
        alt: "Richard Branson holding a model Virgin Atlantic aircraft above his head.",
        caption: "Richard Branson with a model Virgin Atlantic aircraft during the airline’s early years."
      }
    ],
    listingImage: "richard-branson-virgin-atlantic",
    body: [
      { type: "p", html: "Products can be copied. Services can be matched. Competitors can recruit similar people, use similar language and make many of the same promises." },
      { type: "p", html: "They can’t own your history." },
      { type: "p", html: "A strong origin story gives a business something genuinely distinctive. It explains where the organisation came from, what shaped it and why it behaves as it does today." },
      { type: "p", html: "The best examples don’t feel like polished corporate mythology. They contain people, experiments, risks, setbacks and decisions that could only belong to that business." },
      { type: "p", html: "Nike, Apple and Virgin all became global brands. Their beginnings were considerably smaller and more human." },
      { type: "h2", text: "Nike: a coach, a runner and a better shoe" },
      { type: "p", html: "Nike’s story began before the Nike name existed." },
      { type: "p", html: "Bill Bowerman was a track coach with an obsession for helping athletes perform better. Phil Knight was one of his runners. In 1964, they formed Blue Ribbon Sports, initially importing and selling Japanese running shoes." },
      { type: "inset", image: "nike-bill-bowerman" },
      { type: "p", html: "Bowerman kept experimenting with footwear because he wanted to help athletes run faster. Knight saw an opportunity to build a business around better products for runners." },
      { type: "p", html: "That story still supports Nike because the company’s origins connect directly to performance, athlete insight and experimentation." },
      { type: "p", html: "The innovation existed long before Nike had global advertising budgets and famous sponsorship deals." },
      { type: "h2", text: "Apple: making technology feel human" },
      { type: "p", html: "Apple’s story is often told through Steve Jobs, but it was never the work of one person." },
      { type: "p", html: "Jobs brought ambition, judgement and an unusual ability to connect technology with culture. Steve Wozniak brought the engineering expertise behind Apple’s earliest computers. Later, the Macintosh brought together engineers, designers, writers and programmers around a larger idea." },
      { type: "inset", image: "apple-early-team" },
      { type: "p", html: "Computers didn’t need to remain specialist machines understood only by technical experts. They could become personal." },
      { type: "p", html: "The Macintosh was introduced in 1984 as a simpler, more approachable tool, using familiar visual elements including desktop icons and a mouse rather than expecting people to work through programming commands." },
      { type: "p", html: "Apple didn’t simply produce increasingly powerful technology. It helped redefine people’s relationship with it." },
      { type: "h2", text: "Virgin: the outsider prepared to have a go" },
      { type: "p", html: "Virgin began in music before moving into an industry where it had no conventional right to compete." },
      { type: "p", html: "Virgin Atlantic launched in 1984 with one leased Boeing 747 and an ambition to make air travel more enjoyable, energetic and customer-focused." },
      { type: "inset", image: "richard-branson-virgin-atlantic" },
      { type: "p", html: "The image of Richard Branson holding a model aircraft captures something central to the story. It shows an outsider entering a large, established industry with personality, confidence and a willingness to challenge how things were normally done." },
      { type: "p", html: "That challenger mentality became part of the wider Virgin brand." },
      { type: "h2", text: "A story should explain the business, not decorate it" },
      { type: "p", html: "Nike, Apple and Virgin have very different beginnings, but each origin helps explain something still visible in the brand:" },
      { type: "ul", items: [
        "Nike connects its history to athletes, performance and experimentation.",
        "Apple connects its history to collaboration, simplicity and humanising technology.",
        "Virgin connects its history to challenging established categories with energy and personality."
      ] },
      { type: "p", html: "That’s what makes an origin story commercially useful." },
      { type: "p", html: "It provides context for the proposition, culture and ambition. It can help customers understand why the business is credible, help employees recognise what they’re joining and help leaders make future decisions without losing sight of what made the organisation valuable in the first place." },
      { type: "p", html: "Not every early anecdote deserves to become part of the brand. The useful story is the one that still explains something true." },
      { type: "p", html: "It might involve a founder, a customer problem, an unusual partnership, a particular place, a failed idea or years of determined craft." },
      { type: "p", html: "Your story isn’t valuable simply because it happened. It becomes valuable when it helps people understand why your business is different and where it intends to go next." }
    ],
    didYouKnow: [
      "Nike began as Blue Ribbon Sports in 1964, after a partnership between track coach Bill Bowerman and his former athlete Phil Knight.",
      "The Macintosh was created by a multidisciplinary team and launched in 1984 as a more approachable personal computer.",
      "Virgin Atlantic launched with one leased Boeing 747 and operated its first service between London Gatwick and Newark in 1984."
    ],
    related: ["people-do-judge-a-book-by-its-cover", "values-are-better-as-verbs"],
    cta: null
  }
];
